[build]
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16.20.2"
NODE_OPTIONS = "--openssl-legacy-provider"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
